image:
  repository: prodrigestivill/postgres-backup-local
  tag: latest

  ## set to true if you would like to see extra information on logs
  ## It turns BASH and/or NAMI debugging in the image
  ##
  debug: false

  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent

  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## Example:
  ## pullSecrets:
  ##   - myRegistryKeySecretName
  ##
  pullSecrets: []

auth:
  existingPasswordSecret: ""
  postgres_user: ""
  postgres_password: ""

config:
  postgres_host: ""
  postgres_port: 5432
  postgres_db: ""
  postgres_cluster: "TRUE"
  postgres_extra_opts: "" # Use "-Z6" if postgres_db is set
  schedule: "@daily"
  backup_keep_days: 7
  backup_keep_weeks: 4
  backup_keep_months: 6
  healthcheck_port: 8080

## @param extraEnvVars Extra environment variables to add to RabbitMQ pods
## E.g:
## extraEnvVars:
##   - name: FOO
##     value: BAR
##
extraEnvVars: []

## @param replicas Number of pgdump replicas
replicas: 1

## @param persistence Enable pgdump data
persistence:

  ## @param persistence.enabled Enable pgdump data persistence using PVC
  ##
  enabled: false

  ## @param persistence.storageClass PVC Storage Class for pgdump data volume
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: ""

  ## @param persistence.selector Selector to match an existing Persistent Volume
  ## selector:
  ##   matchLabels:
  ##     app: my-app
  ##
  selector: {}

  ## @param persistence.accessMode PVC Access Mode for pgdump data volume
  ##
  accessMode: ReadWriteOnce

  ## @param persistence.existingClaim Provide an existing PersistentVolumeClaims
  ## The value is evaluated as a template
  ## So, for example, the name can depend on .Release or .Chart
  ##
  existingClaim: ""

  ## @param persistence.mountPath The path the volume will be mounted at
  ## Note: useful when using custom pgdump images
  ##
  mountPath: /backups

  ## @param persistence.subPath The subdirectory of the volume to mount to
  ## Useful in dev environments and one PV for multiple services
  ##
  subPath: ""

  ## @param persistence.size PVC Storage Request for pgdump data volume
  ##
  size: 20Gi

  ## @param persistence.annotations Persistence annotations. Evaluated as a template
  ## Example:
  ## annotations:
  ##   example.io/disk-volume-type: SSD
  ##
  annotations: {}

## @param securityContext Security context for pgdump pods
securityContext:
  runAsUser: 999
  runAsGroup: 999
  fsGroup: 999
