apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pgdump.fullname" . }}
  labels:
  {{- include "pgdump.labels" . | nindent 4 }}
data:
  POSTGRES_HOST: {{ .Values.config.postgres_host | quote }}
  POSTGRES_PORT: {{ .Values.config.postgres_port | quote }}
  {{- if not .Values.auth.postgres_db }}
  POSTGRES_DB: {{ .Values.config.postgres_db | quote }}
  {{- end }}
  {{- if not .Values.auth.postgres_cluster }}
  POSTGRES_CLUSTER: {{ .Values.config.postgres_cluster | quote }}
  {{- end }}
  POSTGRES_EXTRA_OPTS: {{ .Values.config.postgres_extra_opts | quote }}
  SCHEDULE: {{ .Values.config.schedule | quote }}
  BACKUP_KEEP_DAYS: {{ .Values.config.backup_keep_days | quote }}
  BACKUP_KEEP_WEEKS: {{ .Values.config.backup_keep_weeks | quote }}
  BACKUP_KEEP_MONTHS: {{ .Values.config.backup_keep_months | quote }}
  HEALTHCHECK_PORT: {{ .Values.config.healthcheck_port | quote }}
{{- if .Values.extraEnvVars }}
{{- range .Values.extraEnvVars }}
  {{ .name }}: {{ .value }}
{{- end }}
{{- end }}
