{{- if not .Values.auth.existingPasswordSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgdump.fullname" . }}
  labels:
  {{- include "pgdump.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.auth.postgres_user | quote }}
  POSTGRES_PASSWORD: {{ .Values.auth.postgres_password | quote }}
{{ end }}